// Enum for Icon Libraries
export enum IconLibraries {
    AntDesignIcons = 'AntDesignIcons',
    BootstrapIcons = 'BootstrapIcons',
    BoxIcons = 'BoxIcons',
    CircumIcons = 'CircumIcons',
    CssGg = 'CssGg',
    Devicons = 'Devicons',
    Feather = 'Feather',
    FlatColorIcons = 'FlatColorIcons',
    FontAwesome5 = 'FontAwesome5',
    FontAwesome6 = 'FontAwesome6',
    GameIcons = 'GameIcons',
    GithubOcticons = 'GithubOcticons',
    GrommetIcons = 'GrommetIcons',
    Heroicons = 'Heroicons',
    Heroicons2 = 'Heroicons2',
    IcoMoonFree = 'IcoMoonFree',
    Icons8LineAwesome = 'Icons8LineAwesome',
    Ionicons4 = 'Ionicons4',
    Ionicons5 = 'Ionicons5',
    Lucide = 'Lucide',
    MaterialDesignIcons = 'MaterialDesignIcons',
    PhosphorIcons = 'PhosphorIcons',
    RadixIcons = 'RadixIcons',
    RemixIcon = 'RemixIcon',
    SimpleIcons = 'SimpleIcons',
    SimpleLineIcons = 'SimpleLineIcons',
    TablerIcons = 'TablerIcons',
    ThemifyIcons = 'ThemifyIcons',
    Typicons = 'Typicons',
    VSCodeIcons = 'VSCodeIcons',
    WeatherIcons = 'WeatherIcons',
}

// Enum for Icon Abbreviations
export enum IconAbbreviations {
    AntDesignIcons = 'ai',
    BootstrapIcons = 'bi',
    BoxIcons = 'bx',
    CircumIcons = 'ci',
    CssGg = 'gg',
    Devicons = 'devicons',
    Feather = 'feather',
    FlatColorIcons = 'fc',
    FontAwesome5 = 'fa5',
    FontAwesome6 = 'fa6',
    GameIcons = 'gi',
    GithubOcticons = 'go',
    GrommetIcons = 'gi',
    Heroicons = 'hi',
    Heroicons2 = 'hi2',
    IcoMoonFree = 'imf',
    Icons8LineAwesome = 'ia',
    Ionicons4 = 'i4',
    Ionicons5 = 'i5',
    Lucide = 'lucide',
    MaterialDesignIcons = 'mdi',
    PhosphorIcons = 'ph',
    RadixIcons = 'ri',
    RemixIcon = 'ri',
    SimpleIcons = 'si',
    SimpleLineIcons = 'sli',
    TablerIcons = 'ti',
    ThemifyIcons = 'ti',
    Typicons = 'ty',
    VSCodeIcons = 'vsc',
    WeatherIcons = 'wi',
}

// Updated map for icon libraries and their corresponding abbreviations
export const iconLibraryMap: { [key in IconLibraries]: IconAbbreviations } = {
    [IconLibraries.AntDesignIcons]: IconAbbreviations.AntDesignIcons,
    [IconLibraries.BootstrapIcons]: IconAbbreviations.BootstrapIcons,
    [IconLibraries.BoxIcons]: IconAbbreviations.BoxIcons,
    [IconLibraries.CircumIcons]: IconAbbreviations.CircumIcons,
    [IconLibraries.CssGg]: IconAbbreviations.CssGg,
    [IconLibraries.Devicons]: IconAbbreviations.Devicons,
    [IconLibraries.Feather]: IconAbbreviations.Feather,
    [IconLibraries.FlatColorIcons]: IconAbbreviations.FlatColorIcons,
    [IconLibraries.FontAwesome5]: IconAbbreviations.FontAwesome5,
    [IconLibraries.FontAwesome6]: IconAbbreviations.FontAwesome6,
    [IconLibraries.GameIcons]: IconAbbreviations.GameIcons,
    [IconLibraries.GithubOcticons]: IconAbbreviations.GithubOcticons,
    [IconLibraries.GrommetIcons]: IconAbbreviations.GrommetIcons,
    [IconLibraries.Heroicons]: IconAbbreviations.Heroicons,
    [IconLibraries.Heroicons2]: IconAbbreviations.Heroicons2,
    [IconLibraries.IcoMoonFree]: IconAbbreviations.IcoMoonFree,
    [IconLibraries.Icons8LineAwesome]: IconAbbreviations.Icons8LineAwesome,
    [IconLibraries.Ionicons4]: IconAbbreviations.Ionicons4,
    [IconLibraries.Ionicons5]: IconAbbreviations.Ionicons5,
    [IconLibraries.Lucide]: IconAbbreviations.Lucide,
    [IconLibraries.MaterialDesignIcons]: IconAbbreviations.MaterialDesignIcons,
    [IconLibraries.PhosphorIcons]: IconAbbreviations.PhosphorIcons,
    [IconLibraries.RadixIcons]: IconAbbreviations.RadixIcons,
    [IconLibraries.RemixIcon]: IconAbbreviations.RemixIcon,
    [IconLibraries.SimpleIcons]: IconAbbreviations.SimpleIcons,
    [IconLibraries.SimpleLineIcons]: IconAbbreviations.SimpleLineIcons,
    [IconLibraries.TablerIcons]: IconAbbreviations.TablerIcons,
    [IconLibraries.ThemifyIcons]: IconAbbreviations.ThemifyIcons,
    [IconLibraries.Typicons]: IconAbbreviations.Typicons,
    [IconLibraries.VSCodeIcons]: IconAbbreviations.VSCodeIcons,
    [IconLibraries.WeatherIcons]: IconAbbreviations.WeatherIcons,
};

export const BACKGROUND_COLOR = 'black';
