export const ICON_LIBRARIES: string[] = [
    'Ant Design Icons',
    'Bootstrap Icons',
    'BoxIcons',
    'Circum Icons',
    'css.gg',
    'Devicons',
    'Feather',
    'Flat Color Icons',
    'Font Awesome 5',
    'Font Awesome 6',
    'Game Icons',
    'Github Octicons icons',
    'Grommet-Icons',
    'Heroicons',
    'Heroicons 2',
    'IcoMoon Free',
    'Icons8 Line Awesome',
    'Ionicons 4',
    'Ionicons 5',
    'Lucide',
    'Material Design icons',
    'Phosphor Icons',
    'Radix Icons',
    'Remix Icon',
    'Simple Icons',
    'Simple Line Icons',
    'Tabler Icons',
    'Themify Icons',
    'Typicons',
    'VS Code Icons',
    'Weather Icons',
];
