import {
    SButton,
    SButtonContainer,
    SButtonLabel,
    SButtonListContainer,
} from '../ButtonIconList';
import {
    LuAccessibility,
    LuActivitySquare,
    LuActivity,
    LuAirVent,
    LuAirplay,
    LuAlarmCheck,
    LuAlarmClockOff,
    LuAlarmClock,
    LuAlarmMinus,
    LuAlarmPlus,
    LuAlbum,
    LuAlertCircle,
    LuAlertOctagon,
    LuAlertTriangle,
    LuAlignCenterHorizontal,
    LuAlignCenterVertical,
    LuAlignCenter,
    LuAlignEndHorizontal,
    LuAlignEndVertical,
    LuAlignHorizontalDistributeCenter,
    LuAlignHorizontalDistributeEnd,
    LuAlignHorizontalDistributeStart,
    LuAlignHorizontalJustifyCenter,
    LuAlignHorizontalJustifyEnd,
    LuAlignHorizontalJustifyStart,
    LuAlignHorizontalSpaceAround,
    LuAlignHorizontalSpaceBetween,
    LuAlignJustify,
    LuAlignLeft,
    LuAlignRight,
    LuAlignStartHorizontal,
    LuAlignStartVertical,
    LuAlignVerticalDistributeCenter,
    LuAlignVerticalDistributeEnd,
    LuAlignVerticalDistributeStart,
    LuAlignVerticalJustifyCenter,
    LuAlignVerticalJustifyEnd,
    LuAlignVerticalJustifyStart,
    LuAlignVerticalSpaceAround,
    LuAlignVerticalSpaceBetween,
    LuAmpersand,
    LuAmpersands,
    LuAnchor,
    LuAngry,
    LuAnnoyed,
    LuAntenna,
    LuAperture,
    LuAppWindow,
    LuApple,
    LuArchiveRestore,
    LuArchive,
    LuAreaChart,
    LuArmchair,
    LuArrowBigDownDash,
    LuArrowBigDown,
    LuArrowBigLeftDash,
    LuArrowBigLeft,
    LuArrowBigRightDash,
    LuArrowBigRight,
    LuArrowBigUpDash,
    LuArrowBigUp,
    LuArrowDown01,
    LuArrowDown10,
    LuArrowDownAZ,
    LuArrowDownCircle,
    LuArrowDownFromLine,
    LuArrowDownLeftFromCircle,
    LuArrowDownLeftSquare,
    LuArrowDownLeft,
    LuArrowDownNarrowWide,
    LuArrowDownRightFromCircle,
    LuArrowDownRightSquare,
    LuArrowDownRight,
    LuArrowDownSquare,
    LuArrowDownToDot,
    LuArrowDownToLine,
    LuArrowDownUp,
    LuArrowDownWideNarrow,
    LuArrowDownZA,
    LuArrowDown,
    LuArrowLeftCircle,
    LuArrowLeftFromLine,
    LuArrowLeftRight,
    LuArrowLeftSquare,
    LuArrowLeftToLine,
    LuArrowLeft,
    LuArrowRightCircle,
    LuArrowRightFromLine,
    LuArrowRightLeft,
    LuArrowRightSquare,
    LuArrowRightToLine,
    LuArrowRight,
    LuArrowUp01,
    LuArrowUp10,
    LuArrowUpAZ,
    LuArrowUpCircle,
    LuArrowUpDown,
    LuArrowUpFromDot,
    LuArrowUpFromLine,
    LuArrowUpLeftFromCircle,
} from 'react-icons/lu';

export const ButtonIconListLu = () => (
    <SButtonListContainer>
        <SButtonContainer>
            <SButton>
                <LuAccessibility size={25} aria-label={'LuAccessibility'} />
            </SButton>
            <SButtonLabel>LuAccessibility</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuActivitySquare size={25} aria-label={'LuActivitySquare'} />
            </SButton>
            <SButtonLabel>LuActivitySquare</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuActivity size={25} aria-label={'LuActivity'} />
            </SButton>
            <SButtonLabel>LuActivity</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAirVent size={25} aria-label={'LuAirVent'} />
            </SButton>
            <SButtonLabel>LuAirVent</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAirplay size={25} aria-label={'LuAirplay'} />
            </SButton>
            <SButtonLabel>LuAirplay</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlarmCheck size={25} aria-label={'LuAlarmCheck'} />
            </SButton>
            <SButtonLabel>LuAlarmCheck</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlarmClockOff size={25} aria-label={'LuAlarmClockOff'} />
            </SButton>
            <SButtonLabel>LuAlarmClockOff</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlarmClock size={25} aria-label={'LuAlarmClock'} />
            </SButton>
            <SButtonLabel>LuAlarmClock</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlarmMinus size={25} aria-label={'LuAlarmMinus'} />
            </SButton>
            <SButtonLabel>LuAlarmMinus</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlarmPlus size={25} aria-label={'LuAlarmPlus'} />
            </SButton>
            <SButtonLabel>LuAlarmPlus</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlbum size={25} aria-label={'LuAlbum'} />
            </SButton>
            <SButtonLabel>LuAlbum</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlertCircle size={25} aria-label={'LuAlertCircle'} />
            </SButton>
            <SButtonLabel>LuAlertCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlertOctagon size={25} aria-label={'LuAlertOctagon'} />
            </SButton>
            <SButtonLabel>LuAlertOctagon</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlertTriangle size={25} aria-label={'LuAlertTriangle'} />
            </SButton>
            <SButtonLabel>LuAlertTriangle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignCenterHorizontal
                    size={25}
                    aria-label={'LuAlignCenterHorizontal'}
                />
            </SButton>
            <SButtonLabel>LuAlignCenterHorizontal</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignCenterVertical
                    size={25}
                    aria-label={'LuAlignCenterVertical'}
                />
            </SButton>
            <SButtonLabel>LuAlignCenterVertical</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignCenter size={25} aria-label={'LuAlignCenter'} />
            </SButton>
            <SButtonLabel>LuAlignCenter</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignEndHorizontal
                    size={25}
                    aria-label={'LuAlignEndHorizontal'}
                />
            </SButton>
            <SButtonLabel>LuAlignEndHorizontal</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignEndVertical
                    size={25}
                    aria-label={'LuAlignEndVertical'}
                />
            </SButton>
            <SButtonLabel>LuAlignEndVertical</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalDistributeCenter
                    size={25}
                    aria-label={'LuAlignHorizontalDistributeCenter'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalDistributeCenter</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalDistributeEnd
                    size={25}
                    aria-label={'LuAlignHorizontalDistributeEnd'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalDistributeEnd</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalDistributeStart
                    size={25}
                    aria-label={'LuAlignHorizontalDistributeStart'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalDistributeStart</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalJustifyCenter
                    size={25}
                    aria-label={'LuAlignHorizontalJustifyCenter'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalJustifyCenter</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalJustifyEnd
                    size={25}
                    aria-label={'LuAlignHorizontalJustifyEnd'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalJustifyEnd</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalJustifyStart
                    size={25}
                    aria-label={'LuAlignHorizontalJustifyStart'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalJustifyStart</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalSpaceAround
                    size={25}
                    aria-label={'LuAlignHorizontalSpaceAround'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalSpaceAround</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignHorizontalSpaceBetween
                    size={25}
                    aria-label={'LuAlignHorizontalSpaceBetween'}
                />
            </SButton>
            <SButtonLabel>LuAlignHorizontalSpaceBetween</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignJustify size={25} aria-label={'LuAlignJustify'} />
            </SButton>
            <SButtonLabel>LuAlignJustify</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignLeft size={25} aria-label={'LuAlignLeft'} />
            </SButton>
            <SButtonLabel>LuAlignLeft</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignRight size={25} aria-label={'LuAlignRight'} />
            </SButton>
            <SButtonLabel>LuAlignRight</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignStartHorizontal
                    size={25}
                    aria-label={'LuAlignStartHorizontal'}
                />
            </SButton>
            <SButtonLabel>LuAlignStartHorizontal</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignStartVertical
                    size={25}
                    aria-label={'LuAlignStartVertical'}
                />
            </SButton>
            <SButtonLabel>LuAlignStartVertical</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalDistributeCenter
                    size={25}
                    aria-label={'LuAlignVerticalDistributeCenter'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalDistributeCenter</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalDistributeEnd
                    size={25}
                    aria-label={'LuAlignVerticalDistributeEnd'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalDistributeEnd</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalDistributeStart
                    size={25}
                    aria-label={'LuAlignVerticalDistributeStart'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalDistributeStart</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalJustifyCenter
                    size={25}
                    aria-label={'LuAlignVerticalJustifyCenter'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalJustifyCenter</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalJustifyEnd
                    size={25}
                    aria-label={'LuAlignVerticalJustifyEnd'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalJustifyEnd</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalJustifyStart
                    size={25}
                    aria-label={'LuAlignVerticalJustifyStart'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalJustifyStart</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalSpaceAround
                    size={25}
                    aria-label={'LuAlignVerticalSpaceAround'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalSpaceAround</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAlignVerticalSpaceBetween
                    size={25}
                    aria-label={'LuAlignVerticalSpaceBetween'}
                />
            </SButton>
            <SButtonLabel>LuAlignVerticalSpaceBetween</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAmpersand size={25} aria-label={'LuAmpersand'} />
            </SButton>
            <SButtonLabel>LuAmpersand</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAmpersands size={25} aria-label={'LuAmpersands'} />
            </SButton>
            <SButtonLabel>LuAmpersands</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAnchor size={25} aria-label={'LuAnchor'} />
            </SButton>
            <SButtonLabel>LuAnchor</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAngry size={25} aria-label={'LuAngry'} />
            </SButton>
            <SButtonLabel>LuAngry</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAnnoyed size={25} aria-label={'LuAnnoyed'} />
            </SButton>
            <SButtonLabel>LuAnnoyed</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAntenna size={25} aria-label={'LuAntenna'} />
            </SButton>
            <SButtonLabel>LuAntenna</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAperture size={25} aria-label={'LuAperture'} />
            </SButton>
            <SButtonLabel>LuAperture</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAppWindow size={25} aria-label={'LuAppWindow'} />
            </SButton>
            <SButtonLabel>LuAppWindow</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuApple size={25} aria-label={'LuApple'} />
            </SButton>
            <SButtonLabel>LuApple</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArchiveRestore size={25} aria-label={'LuArchiveRestore'} />
            </SButton>
            <SButtonLabel>LuArchiveRestore</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArchive size={25} aria-label={'LuArchive'} />
            </SButton>
            <SButtonLabel>LuArchive</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuAreaChart size={25} aria-label={'LuAreaChart'} />
            </SButton>
            <SButtonLabel>LuAreaChart</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArmchair size={25} aria-label={'LuArmchair'} />
            </SButton>
            <SButtonLabel>LuArmchair</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigDownDash
                    size={25}
                    aria-label={'LuArrowBigDownDash'}
                />
            </SButton>
            <SButtonLabel>LuArrowBigDownDash</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigDown size={25} aria-label={'LuArrowBigDown'} />
            </SButton>
            <SButtonLabel>LuArrowBigDown</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigLeftDash
                    size={25}
                    aria-label={'LuArrowBigLeftDash'}
                />
            </SButton>
            <SButtonLabel>LuArrowBigLeftDash</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigLeft size={25} aria-label={'LuArrowBigLeft'} />
            </SButton>
            <SButtonLabel>LuArrowBigLeft</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigRightDash
                    size={25}
                    aria-label={'LuArrowBigRightDash'}
                />
            </SButton>
            <SButtonLabel>LuArrowBigRightDash</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigRight size={25} aria-label={'LuArrowBigRight'} />
            </SButton>
            <SButtonLabel>LuArrowBigRight</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigUpDash size={25} aria-label={'LuArrowBigUpDash'} />
            </SButton>
            <SButtonLabel>LuArrowBigUpDash</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowBigUp size={25} aria-label={'LuArrowBigUp'} />
            </SButton>
            <SButtonLabel>LuArrowBigUp</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDown01 size={25} aria-label={'LuArrowDown01'} />
            </SButton>
            <SButtonLabel>LuArrowDown01</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDown10 size={25} aria-label={'LuArrowDown10'} />
            </SButton>
            <SButtonLabel>LuArrowDown10</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownAZ size={25} aria-label={'LuArrowDownAZ'} />
            </SButton>
            <SButtonLabel>LuArrowDownAZ</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownCircle size={25} aria-label={'LuArrowDownCircle'} />
            </SButton>
            <SButtonLabel>LuArrowDownCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownFromLine
                    size={25}
                    aria-label={'LuArrowDownFromLine'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownFromLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownLeftFromCircle
                    size={25}
                    aria-label={'LuArrowDownLeftFromCircle'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownLeftFromCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownLeftSquare
                    size={25}
                    aria-label={'LuArrowDownLeftSquare'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownLeftSquare</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownLeft size={25} aria-label={'LuArrowDownLeft'} />
            </SButton>
            <SButtonLabel>LuArrowDownLeft</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownNarrowWide
                    size={25}
                    aria-label={'LuArrowDownNarrowWide'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownNarrowWide</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownRightFromCircle
                    size={25}
                    aria-label={'LuArrowDownRightFromCircle'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownRightFromCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownRightSquare
                    size={25}
                    aria-label={'LuArrowDownRightSquare'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownRightSquare</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownRight size={25} aria-label={'LuArrowDownRight'} />
            </SButton>
            <SButtonLabel>LuArrowDownRight</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownSquare size={25} aria-label={'LuArrowDownSquare'} />
            </SButton>
            <SButtonLabel>LuArrowDownSquare</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownToDot size={25} aria-label={'LuArrowDownToDot'} />
            </SButton>
            <SButtonLabel>LuArrowDownToDot</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownToLine size={25} aria-label={'LuArrowDownToLine'} />
            </SButton>
            <SButtonLabel>LuArrowDownToLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownUp size={25} aria-label={'LuArrowDownUp'} />
            </SButton>
            <SButtonLabel>LuArrowDownUp</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownWideNarrow
                    size={25}
                    aria-label={'LuArrowDownWideNarrow'}
                />
            </SButton>
            <SButtonLabel>LuArrowDownWideNarrow</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDownZA size={25} aria-label={'LuArrowDownZA'} />
            </SButton>
            <SButtonLabel>LuArrowDownZA</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowDown size={25} aria-label={'LuArrowDown'} />
            </SButton>
            <SButtonLabel>LuArrowDown</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowLeftCircle size={25} aria-label={'LuArrowLeftCircle'} />
            </SButton>
            <SButtonLabel>LuArrowLeftCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowLeftFromLine
                    size={25}
                    aria-label={'LuArrowLeftFromLine'}
                />
            </SButton>
            <SButtonLabel>LuArrowLeftFromLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowLeftRight size={25} aria-label={'LuArrowLeftRight'} />
            </SButton>
            <SButtonLabel>LuArrowLeftRight</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowLeftSquare size={25} aria-label={'LuArrowLeftSquare'} />
            </SButton>
            <SButtonLabel>LuArrowLeftSquare</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowLeftToLine size={25} aria-label={'LuArrowLeftToLine'} />
            </SButton>
            <SButtonLabel>LuArrowLeftToLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowLeft size={25} aria-label={'LuArrowLeft'} />
            </SButton>
            <SButtonLabel>LuArrowLeft</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowRightCircle
                    size={25}
                    aria-label={'LuArrowRightCircle'}
                />
            </SButton>
            <SButtonLabel>LuArrowRightCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowRightFromLine
                    size={25}
                    aria-label={'LuArrowRightFromLine'}
                />
            </SButton>
            <SButtonLabel>LuArrowRightFromLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowRightLeft size={25} aria-label={'LuArrowRightLeft'} />
            </SButton>
            <SButtonLabel>LuArrowRightLeft</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowRightSquare
                    size={25}
                    aria-label={'LuArrowRightSquare'}
                />
            </SButton>
            <SButtonLabel>LuArrowRightSquare</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowRightToLine
                    size={25}
                    aria-label={'LuArrowRightToLine'}
                />
            </SButton>
            <SButtonLabel>LuArrowRightToLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowRight size={25} aria-label={'LuArrowRight'} />
            </SButton>
            <SButtonLabel>LuArrowRight</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUp01 size={25} aria-label={'LuArrowUp01'} />
            </SButton>
            <SButtonLabel>LuArrowUp01</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUp10 size={25} aria-label={'LuArrowUp10'} />
            </SButton>
            <SButtonLabel>LuArrowUp10</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUpAZ size={25} aria-label={'LuArrowUpAZ'} />
            </SButton>
            <SButtonLabel>LuArrowUpAZ</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUpCircle size={25} aria-label={'LuArrowUpCircle'} />
            </SButton>
            <SButtonLabel>LuArrowUpCircle</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUpDown size={25} aria-label={'LuArrowUpDown'} />
            </SButton>
            <SButtonLabel>LuArrowUpDown</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUpFromDot size={25} aria-label={'LuArrowUpFromDot'} />
            </SButton>
            <SButtonLabel>LuArrowUpFromDot</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUpFromLine size={25} aria-label={'LuArrowUpFromLine'} />
            </SButton>
            <SButtonLabel>LuArrowUpFromLine</SButtonLabel>
        </SButtonContainer>
        <SButtonContainer>
            <SButton>
                <LuArrowUpLeftFromCircle
                    size={25}
                    aria-label={'LuArrowUpLeftFromCircle'}
                />
            </SButton>
            <SButtonLabel>LuArrowUpLeftFromCircle</SButtonLabel>
        </SButtonContainer>
    </SButtonListContainer>
);

export default ButtonIconListLu;
